from app.infrastructure.http.controllers.certificate_controller import CertificateController
from .certificate_routes import get_certificate_routes
from app.application.usecases.certificates.generate_certificate_usecase import GenerateCertificateUseCase

controller = CertificateController(GenerateCertificateUseCase)

certificate_router = get_certificate_routes(controller)
